### ISSUE TITLE
Discrepancies in the dataset

### ISSUE THREAD

**Issue by RDXSun** [TrustworthyComp/mcfend#1]
如题，感觉被骗了

**Comment by TrustworthyComp** [comment]
您好, 感谢您对我们工作的关注，MCFEND的数据集下载链接位于[https://drive.google.com/drive/folders/1tflhQTkMT_gTTwEw3ESfKS7Sr5w__5u5]，但我们注意到您提到的可能存在误解。能否麻烦您详细指出论文中可能存在差异的地方，我们将仔细核对，并确保提供正确版本的数据！

**Comment by TrustworthyComp** [comment]
Hi @RDXSun, Since sufficient information has not been provided, we are closing this issue for now. If there are any follow-up questions or more recent information regarding discrepancies in the dataset, please feel free to reopen this issue at any time. We will carefully verify and ensure that the correct version of the data is provided!
